name: Scheduled Workflow

on:

 push:
     branches:
       - master

jobs:
   k6_load_test:
     name: k6 Load Test
     runs-on: ubuntu-latest
     steps:
     - name: Checkout
       uses: actions/checkout@v1
     - name: Run local k6 test
       uses: k6io/action@v0.1
       with:
         filename: test.js     
     - name: Send a Slack Notification
       uses: 8398a7/action-slack@v3
       with:
         channel: '#personal-channel'
         status: custom
         fields: workflow,job,commit,repo,ref,author,took
         custom_payload: |
           {
             username: 'action-slack',
             icon_emoji: ':octocat:',
             attachments: [{
             color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning' ,
             title: `${process.env.AS_WORKFLOW}\n${process.env.AS_JOB} (${process.env.AS_COMMIT}) of ${process.env.AS_REPO}@master by ${process.env.AS_AUTHOR}`,  
             text: '${{ job.status }}' === 'success' ? 'SUCCESS' : '${{ job.status }}' === 'failure' ? 'Service failed to run but dont worry Gintaa is already analysing the failure root cause' : 'warning'
            }]
           }
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # optional
         SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
       if: always()
